name: Bug Report
description: Create a report to help me improve the shader pack
title: "[Bug Report]: "
labels: bug
assignees: 
  - TechDevOnGitHub

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. *etc.*
        4. See error
    validations:
      required: true
  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
  - type: textarea
    id: bug-hardware-specs
    attributes:
      label: Hardware specification
      placeholder: - GPU and/or installed graphics driver *(with driver version)*
  - type: textarea
    id: bug-software-specs
    attributes:
      label: Software specification
      placeholder: |
        - Minecraft Version
        - Shader Engine + Version (e.g Opitifine HD U H9, Iris 2.0.4)
        - Instaeed mods (if any)
  - type: markdown
    attributes:
      value: > Bugs introduced by 3rd-parte game clients **are not** being fixed
  - type: textarea
    id: bug-additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, if necessary.
